#!/usr/bin/env bash

openfortivpn -c /etc/.fortivpnconf &
vpn_id=$!
sleep 5
echo "Clean route"
ip route add 192.168.2.236 dev ppp0
ip route add 192.168.2.238 dev ppp0
ip route add 192.168.2.250 dev ppp0
ip route del 112.86.83.102
wait $vpn_id

function clean {
	kill $vpn_id
}

trap clean EXIT
