# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ata_piix" "uhci_hcd" "sr_mod" "virtio_pci" "virtio_blk" "virtio_scsi" "xen_blkfront" "vmw_pvscsi" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "console=ttyS0,115200n8" "console=tty0" ];
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/vda"; # or "nodev" for efi only

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/btrfs-root" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/af111b8a-cfaf-4d76-a3a2-18e530085652";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  swapDevices = [{ device = "/swap/swapfile"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
