{
  inputs,
  myvars,
  ...
}:
let
  inherit (inputs) impermanence agenix;
  inherit (myvars) username;
in
{
  imports = [
    impermanence.nixosModules.impermanence
    agenix.nixosModules.default
  ];

  # There are two ways to clear the root filesystem on every boot:
  ##  1. use tmpfs for /
  ##  2. (btrfs/zfs only)take a blank snapshot of the root filesystem and revert to it on every boot via:
  ##     boot.initrd.postDeviceCommands = ''
  ##       mkdir -p /run/mymount
  ##       mount -o subvol=/ /dev/disk/by-uuid/UUID /run/mymount
  ##       btrfs subvolume delete /run/mymount
  ##       btrfs subvolume snapshot / /run/mymount
  ##     '';
  #
  #  See also https://grahamc.com/blog/erase-your-darlings/

  # Use ssh key in persist volume to avoid bootup issue
  age.identityPaths = [
    "/persistent/etc/ssh/ssh_host_ed25519_key"
    "/persistent/etc/ssh/ssh_host_rsa_key"
  ];

  # NOTE: impermanence only mounts the directory/file list below to /persistent
  # If the directory/file already exists in the root filesystem, you should
  # move those files/directories to /persistent first!
  environment.persistence."/persistent" = {
    # sets the mount option x-gvfs-hide on all the bind mounts
    # to hide them from the file manager
    hideMounts = true;
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      "/etc/nix/inputs"
      "/etc/rancher"
      "/etc/asusd"
      "/etc/rclone"
      # "/etc/secureboot" # lanzaboote - secure boot
      # my secrets
      "/etc/agenix/"

      "/var/log"
      "/var/lib"
      "/var/jfsCache" # JFS Cache dir
      "/var/cache"
      "/data"

      # created by modules/nixos/misc/fhs-fonts.nix
      # for flatpak apps
      # "/usr/share/fonts"
      # "/usr/share/icons"
    ];
    files = [
      "/etc/machine-id"
    ];

    # the following directories will be passed to /persistent/home/$USER
    users.${username} = {
      directories = [
        "nixos-configs"

        # Daily
        "Codes"
        "Desktop"
        "Documents"
        "Downloads"
        "Music"
        "Pictures"
        "Videos"
        "Sync"
        "Onedrive"

        # Mail
        "Mail"
        ".offlineimap"
        ".passage"

        {
          directory = ".gnupg";
          mode = "0700";
        }
        {
          directory = ".ssh";
          mode = "0700";
        }

        # neovim / remmina / flatpak / ...
        ".local/share"
        ".local/state"

        # States
        ".cache/betterlockscreen"
        ".cache/nix"
        ".cache/onedriver"
        ".cache/zellij"
        ".cache/restic"
        ".cache/tlrc"
        ".vnc"

        # Configs
        ".config/autostart"
        ".config/clash-verge"
        ".config/DingTalk"
        ".config/Kingsoft"
        ".config/QQ"
        ".config/lx-music-desktop"
        ".config/matlab"
        ".config/obs-studio"
        ".config/Typora"
        ".config/pulse" # PulseAudio state
        ".config/rbw" # bitwarden accounts
        ".config/nnn" # NNN bookmarks
        ".config/fcitx5"
        ".config/copyq"
        ".config/Bitwarden"
        ".config/rustdesk"
        ".config/OpenTabletDriver"
        ".config/xournalpp"
        ".config/sunshine"
        ".config/Moonlight Game Streaming Project"
        ".config/rclone"

        # Logseq / Zotero
        ".config/Logseq"
        ".logseq"
        ".zotero"
        "Zotero"

        # Matlab
        ".MathWorks"
        ".matlab"
        ".MATLABConnector"

        # browsers
        ".mozilla"
        ".config/google-chrome"

        # language package managers
        ".cargo" # rust
        "go"
        ".npm"
        ".conda" # generated by `conda-shell`
        ".m2" # maven
        ".gradle" # gradle
        ".pyenv"
        ".eclipse"

        # misc
        ".pki"
        ".snipaste"
        ".steam" # steam gamees
        ".xwechat"
        ".config/github-copilot" # nvim plugins
        "Waytech" # clouddrive2

        # cloud native
        {
          # pulumi - infrastructure as code
          directory = ".pulumi";
          mode = "0700";
        }
        {
          directory = ".aws";
          mode = "0700";
        }
        {
          directory = ".docker";
          mode = "0700";
        }
        {
          directory = ".kube";
          mode = "0700";
        }

        # remote desktop
        ".config/remmina"
        ".config/freerdp"

        # vscode
        ".vscode"
        ".vscode-insiders"
        ".config/Code/User"
        ".config/Code - Insiders/User"

        # SiYuan
        # ".config/SiYuan"
        ".config/SiYuan-Electron"
        ".config/siyuan"
        "SiYuan"
      ];
      files = [
        ".cache/rofi3.druncache"
      ];
    };
  };

  # Impermanence will copy permissions from source dir
  # Chown to <username>:users
  systemd.tmpfiles.rules = [ "d /persistent/home/${username} 700 ${username} users" ];
}
