# Generated by ./update.sh - do not update manually!
# Last updated: 2025-03-15
{
  version = "12.8.2.20327";
  pro_arm64_url = "https://wps-linux-365.wpscdn.cn/wps/download/ep/Linux365/20327/wps-office_12.8.2.20327.AK.preload.sw_arm64.deb";
  pro_amd64_url = "https://wps-linux-365.wpscdn.cn/wps/download/ep/Linux365/20327/wps-office_12.8.2.20327.AK.preload.sw_amd64.deb";
  pro_arm64_hash = "sha256-jBxYGISLDS/wFgHKXbxtWtaJ69BzB9NaMdUyeTBD5/M=";
  pro_amd64_hash = "sha256-N+2n6i7RCoKjAQ6Pds/dpfupnKR624RUiGj2cQQFpHk=";
}
