{ lib }:
{
  username = "ltrump";
  userfullname = "L-Trump";
  useremail = "ltrump@163.com";
  networking = import ./networking.nix { inherit lib; };
  nixpkgs-config = import ./nixpkgs-config.nix { inherit lib; };
  containers = import ./containers.nix { inherit lib; };
  # networking = import ./networking.nix { inherit lib; };
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....5g64rxLgKEUvG7grFLJT80$0Y248QHdQ2EY8LTrahcNMETxRFLw1m9T.ppyOCnzKp.";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIELKxC3ntw44oEB+HnFwrDQOudiVmf9XnO3W+P2HA+1N ltrump@mbgt"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL6Ic0uPufIiXRVYx/RN1lJIDHCreWEDALDifiLbgTkH ltrump@rog"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB3HTnnSqW08xkgIEKHyRyIB9H2qEkRAnbe/pOlN3uoT ltrump@n100"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIJvcGCqT9GbTjxRHUFL8wp6nNXKIvtiFGhZD05yrFSb ltrump@fallback"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIy+DeKN/Lzov2h8cDsOjOwtRAA6c5WcTlQCwUpv9zB0 ltrump@oldfallback"
  ];
}
