{ lib }: {
  username = "ltrump";
  userfullname = "L-Trump";
  useremail = "ltrump@163.com";
  # networking = import ./networking.nix { inherit lib; };
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....NCcYpFqlLLfDqBKOQq7iO/$vJMZrfdf5uHC4vVGTHESWKPidEyuDkrvzcAeCYiotiB";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4EX2pnEnMWLxi5Es3sGtrF11xi7vPv+DS3A5nFWlQ2 ltrump@mbgt"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIJvcGCqT9GbTjxRHUFL8wp6nNXKIvtiFGhZD05yrFSb ltrump@fallback"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIy+DeKN/Lzov2h8cDsOjOwtRAA6c5WcTlQCwUpv9zB0 ltrump@oldfallback"
  ];
}
