#!/bin/sh
while :; do case $1 in
	--getsavefilename) file="$2" break ;;
	--getopenfilename) dir="$2" break ;;
	--version)
		printf ""
		exit
		;;
	--*) shift ;;
	*) break ;;
	esac done

! [ -d "$dir" ] && dir="${file%/*}"
! [ -d "$dir" ] && dir="$HOME/Downloads"
file="${file##/*/}"

kitty --class picker -T "NNN File Picker" -e sh -c "cd $dir && nnn -J -p - '$file' | awk '{ print system(\"[ -d '\''\"\$0\"'\'' ]\") ? \$0 : \$0\"/$file\" }' > /proc/$$/fd/1"
