{
  config,
  pkgs,
  lib,
  ...
}:
let
  # Rebuild mail-scripts (same contents as mail/default.nix; the store path is
  # deduplicated).
  mail-scripts = pkgs.mkScriptsPackage "mail-scripts" ./scripts;
in
{
  # goimapnotify: generated by Home Manager's services.imapnotify module from
  # accounts.email.accounts.
  # - One systemd user service is generated per account (imapnotify-<account>).
  # - IMAP IDLE watches for new mail -> onNotify runs my-mail-sync ->
  #   onNotifyPost runs offlineimap-notify.
  # - Configuration is generated at ~/.config/imapnotify/<account>.json;
  #   the old agenix goimapnotify.yaml is no longer used.
  services.imapnotify = {
    enable = true;

    path = [
      mail-scripts
      pkgs.offlineimap
      pkgs.passage
      config.programs.notmuch.package
    ];
  };
}
