{
  config,
  pkgs,
  lib,
  ...
}:
{
  # offlineimap: configuration is generated by Home Manager's official module
  # from accounts.email.accounts.
  # - The offlineimap configuration is generated at
  #   ~/.config/offlineimap/config; it is no longer managed by agenix.
  # - Passwords are retrieved at runtime by get_settings.py's
  #   get_pass(service, cmd), which executes passage.
  # - The per-account postSyncHookCommand updates the notmuch index after sync;
  #   it is defined in the public home/tui/mail/accounts.nix structure.
  programs.offlineimap = {
    enable = true;

    extraConfig.general = {
      ui = "basic";
    };
  };
}
