#!/usr/bin/env sh
save="$3"
suggest="$4"
out="$5"
file="${suggest##/*/}"

echo "$@" >/tmp/ffnnn.log
echo "$(env)" >>/tmp/ffnnn.log

if [ "$save" = 1 ]; then
    touch "$suggest"
fi

kitty --class picker -T "nnn file picker" -e fish -ilc "nnn -p - '$suggest' | awk '{ print system(\"[ -d '\''\"\$0\"'\'' ]\") ? \$0 : \$0\"/$file\" }' > '$out'"

if [ "$save" = 1 ]; then
    if [ ! -s "$out" ] || [ ! -s "$suggest" ]; then
        rm "$suggest"
    fi
fi
